baseurl = "https://www.jetprobe.com/"
languageCode = "en-us"
title = "Jet Probe"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Shad Amez"
	description = "JetProbe documentation"
	copyright = "Shad Amez. Released under the Apache license"

	# Repository
	provider = "GitHub"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "white"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[[menu.main]]
  name = "Guide to JetProbe"
	url = "/docs/"
	weight = 0
	identifier = "docsMenu"

[[menu.main]]
	name   = "Introduction"
	url    = "/docs/introduction/"
	parent = "docsMenu"
	weight = 10

[[menu.main]]
	name   = "Getting started"
	url    = "/docs/getting-started/"
	parent = "docsMenu"
	weight = 20


[[menu.main]]
	name   = "Roadmap"
	url    = "/docs/roadmap/"
	parent = "docsMenu"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "/docs/license/"
	parent = "docsMenu"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
